from django.urls import path
from . import views

urlpatterns = [
    ###
    path('dash/', views.ChartDash, name="chart-dash"),
    path('dash/<str:year>/', views.ChartDashYear, name="chart-dash-year"),
    #
    path('api/pay/dash/', views.APIPayDash.as_view()),
    path('api/pay/mopcat/', views.APIPayMopCat.as_view()),
    path('api/pay/cat/', views.APIPayCat.as_view()),
    path('api/pay/sec/', views.APIPaySec.as_view()),
    path('api/pay/cap/', views.APIPayCap.as_view()),
    path('api/pay/year/<str:year>/', views.APIPayYear.as_view()),
    path('api/pay/mopcat/<str:year>/', views.APIPayMopCatYear.as_view()),
    path('api/pay/cat/<str:year>/', views.APIPayCatYear.as_view()),
    path('api/pay/sec/<str:year>/', views.APIPaySecYear.as_view()),
    path('api/pay/cap/<str:year>/', views.APIPayCapYear.as_view()),
    #
    path('api/pay/fis/dash/', views.APIPayFisDash.as_view()),
    path('api/pay/fis/mopcat/', views.APIPayFisMopCat.as_view()),
    path('api/pay/fis/cat/', views.APIPayFisCat.as_view()),
    path('api/pay/fis/sec/', views.APIPayFisSec.as_view()),
    path('api/pay/fis/cap/', views.APIPayFisCap.as_view()),
    path('api/pay/fis/year/<str:year>/', views.APIPayFisYear.as_view()),
    path('api/pay/fis/mopcat/<str:year>/', views.APIPayFisMopCatYear.as_view()),
    path('api/pay/fis/cat/<str:year>/', views.APIPayFisCatYear.as_view()),
    path('api/pay/fis/sec/<str:year>/', views.APIPayFisSecYear.as_view()),
    path('api/pay/fis/cap/<str:year>/', views.APIPayFisCapYear.as_view()),
    #
    path('api/pay/ann/dash/', views.APIPayAnnDash.as_view()),
    path('api/pay/ann/mopcat/', views.APIPayAnnMopCat.as_view()),
    path('api/pay/ann/cat/', views.APIPayAnnCat.as_view()),
    path('api/pay/ann/sec/', views.APIPayAnnSec.as_view()),
    path('api/pay/ann/cap/', views.APIPayAnnCap.as_view()),
    path('api/pay/ann/year/<str:year>/', views.APIPayAnnYear.as_view()),
    path('api/pay/ann/mopcat/<str:year>/', views.APIPayAnnMopCatYear.as_view()),
    path('api/pay/ann/cat/<str:year>/', views.APIPayAnnCatYear.as_view()),
    path('api/pay/ann/sec/<str:year>/', views.APIPayAnnSecYear.as_view()),
    path('api/pay/ann/cap/<str:year>/', views.APIPayAnnCapYear.as_view()),
    ###
    #
    path('div/api/pay/dash/<str:pk>/', views.divAPIPayDash.as_view()),
    path('div/api/pay/mopcat/<str:pk>/', views.divAPIPayMopCat.as_view()),
    path('div/api/pay/cat/<str:pk>/', views.divAPIPayCat.as_view()),
    path('div/api/pay/sec/<str:pk>/', views.divAPIPaySec.as_view()),
    path('div/api/pay/cap/<str:pk>/', views.divAPIPayCap.as_view()),
    path('div/api/pay/year/<str:pk>/<str:year>/', views.divAPIPayYear.as_view()),
    path('div/api/pay/mopcat/<str:pk>/<str:year>/', views.divAPIPayMopCatYear.as_view()),
    path('div/api/pay/cat/<str:pk>/<str:year>/', views.divAPIPayCatYear.as_view()),
    path('div/api/pay/sec/<str:pk>/<str:year>/', views.divAPIPaySecYear.as_view()),
    path('div/api/pay/cap/<str:pk>/<str:year>/', views.divAPIPayCapYear.as_view()),
    #
    path('div/api/pay/fis/dash/<str:pk>/', views.divAPIPayFisDash.as_view()),
    path('div/api/pay/fis/mopcat/<str:pk>/', views.divAPIPayFisMopCat.as_view()),
    path('div/api/pay/fis/cat/<str:pk>/', views.divAPIPayFisCat.as_view()),
    path('div/api/pay/fis/sec/<str:pk>/', views.divAPIPayFisSec.as_view()),
    path('div/api/pay/fis/cap/<str:pk>/', views.divAPIPayFisCap.as_view()),
    path('div/api/pay/fis/year/<str:pk>/<str:year>/', views.divAPIPayFisYear.as_view()),
    path('div/api/pay/fis/mopcat/<str:pk>/<str:year>/', views.divAPIPayFisMopCatYear.as_view()),
    path('div/api/pay/fis/cat/<str:pk>/<str:year>/', views.divAPIPayFisCatYear.as_view()),
    path('div/api/pay/fis/sec/<str:pk>/<str:year>/', views.divAPIPayFisSecYear.as_view()),
    path('div/api/pay/fis/cap/<str:pk>/<str:year>/', views.divAPIPayFisCapYear.as_view()),
    #
    path('div/api/pay/ann/dash/<str:pk>/', views.divAPIPayAnnDash.as_view()),
    path('div/api/pay/ann/mopcat/<str:pk>/', views.divAPIPayAnnMopCat.as_view()),
    path('div/api/pay/ann/cat/<str:pk>/', views.divAPIPayAnnCat.as_view()),
    path('div/api/pay/ann/sec/<str:pk>/', views.divAPIPayAnnSec.as_view()),
    path('div/api/pay/ann/cap/<str:pk>/', views.divAPIPayAnnCap.as_view()),
    path('div/api/pay/ann/year/<str:pk>/<str:year>/', views.divAPIPayAnnYear.as_view()),
    path('div/api/pay/ann/mopcat/<str:pk>/<str:year>/', views.divAPIPayAnnMopCatYear.as_view()),
    path('div/api/pay/ann/cat/<str:pk>/<str:year>/', views.divAPIPayAnnCatYear.as_view()),
    path('div/api/pay/ann/sec/<str:pk>/<str:year>/', views.divAPIPayAnnSecYear.as_view()),
    path('div/api/pay/ann/cap/<str:pk>/<str:year>/', views.divAPIPayAnnCapYear.as_view()),
]