# Generated by Django 4.0 on 2024-01-10 12:12

import contract.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project', '0001_initial'),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Numeru Kontratu')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Montante Kontratu')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('proc_year', models.IntegerField(blank=True, null=True, verbose_name='Tinan Tender')),
                ('company_type', models.CharField(choices=[('Single', 'Single'), ('JV', 'JV')], max_length=6, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Deskrisaun')),
                ('is_fiscal', models.BooleanField(default=False, null=True, verbose_name='Kontratu Fiscal')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_lock', models.BooleanField(blank=True, default=False, null=True)),
                ('is_ready', models.BooleanField(blank=True, default=False, null=True)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('is_stop', models.BooleanField(blank=True, default=False, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('stop_comment', models.TextField(blank=True, null=True, verbose_name='Rajaun Hapara')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='project.project')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='custom.statusimp')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='custom.ctype', verbose_name='Tipu Aprovisionamentu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Deskrisaun')),
                ('is_confirm', models.BooleanField(blank=True, default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContractYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Montante')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Tinan')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractyear', to='contract.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, null=True, verbose_name='Deskrisaun')),
                ('file', models.FileField(null=True, upload_to=contract.utils.upload_cont, verbose_name='Anexu')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractfiles', to='contract.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractcomp', to='company.company')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractcomp', to='contract.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('com_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('bal_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, null=True)),
                ('bal_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('phys_prog', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contpay', to='contract.contract')),
                ('contractyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contpay', to='contract.contractyear')),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Numeru')),
                ('end_date', models.DateField(null=True)),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Deskrisaun')),
                ('is_confirm', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendmentperiod', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='AmendmentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Numeru')),
                ('total', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='Deskrisaun')),
                ('is_confirm', models.BooleanField(blank=True, default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amendmentamount', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('end_date', models.DateField(null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amendment', to='contract.contract')),
            ],
        ),
    ]
