# Generated by Django 5.0.6 on 2024-06-12 02:06

import contract.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contractyear_is_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Joint Venture', 'Join Venture')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_fiscal',
            field=models.BooleanField(default=False, null=True, verbose_name='Kontratu Fiskal'),
        ),
        migrations.AlterField(
            model_name='contractfiles',
            name='file',
            field=models.FileField(null=True, upload_to=contract.utils.upload_cont, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='contractyear',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tinan Kontrantu'),
        ),
    ]
