# Generated by Django 5.0.6 on 2024-06-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_company_type_alter_contract_is_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Joint Venture', 'Joint Venture')], max_length=16, null=True),
        ),
    ]
