# Generated by Django 5.0.6 on 2024-06-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contract_proc_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='proc_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tinan Tender'),
        ),
    ]
