# Generated by Django 4.2.13 on 2024-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_contract_proc_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amendment',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='amendmentperiod',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Numeru Kontratu Foun'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Numeru Kontratu'),
        ),
    ]
