# Generated by Django 4.0 on 2024-01-10 12:16

from django.db import migrations, models
import django.db.models.deletion
import ver.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contract', '0001_initial'),
        ('employee', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='Numeru')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Assuntu')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Ikus')),
                ('file', models.FileField(blank=True, null=True, upload_to=ver.utils.upload_ver, verbose_name='Anexu')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Komentariu UVIP')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back', models.BooleanField(blank=True, default=False, null=True)),
                ('back_comment', models.TextField(blank=True, null=True, verbose_name='Komentariu')),
                ('is_end', models.BooleanField(blank=True, default=False, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('cont', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to='contract.contract')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to='invoice.invoice')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to='custom.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='VerTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(blank=True, default=False, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('is_uvip_out', models.BooleanField(blank=True, default=False, null=True)),
                ('date_uvip_out', models.DateField(blank=True, null=True)),
                ('is_sec_in_1', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_in_1', models.DateField(blank=True, null=True)),
                ('is_sec_out_1', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_out_1', models.DateField(blank=True, null=True)),
                ('is_eng_in', models.BooleanField(blank=True, default=False, null=True)),
                ('date_eng_in', models.DateField(blank=True, null=True)),
                ('is_eng_out', models.BooleanField(blank=True, default=False, null=True)),
                ('date_eng_out', models.DateField(blank=True, null=True)),
                ('is_sec_in_2', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_in_2', models.DateField(blank=True, null=True)),
                ('is_sec_out_2', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_out_2', models.DateField(blank=True, null=True)),
                ('is_uvip_in', models.BooleanField(blank=True, default=False, null=True)),
                ('date_uvip_in', models.DateField(blank=True, null=True)),
                ('is_end', models.BooleanField(blank=True, default=False, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('stages', models.CharField(blank=True, max_length=50, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('ver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vertracks', to='ver.ver')),
            ],
        ),
        migrations.CreateModel(
            name='VerSecEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='Numeru')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Assuntu')),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Deskrisaun')),
                ('file', models.FileField(null=True, upload_to=ver.utils.upload_versec, verbose_name='Anexu')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('is_send_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_eng_back', models.BooleanField(blank=True, default=False, null=True)),
                ('is_eng_read', models.BooleanField(blank=True, default=False, null=True)),
                ('eng_comments', models.TextField(blank=True, null=True, verbose_name='Komentariu Engineiru')),
                ('file2', models.FileField(blank=True, null=True, upload_to=ver.utils.upload_versec, verbose_name='Anexu')),
                ('sec_comments', models.TextField(blank=True, null=True, verbose_name='Komentariu Seksaun')),
                ('file3', models.FileField(blank=True, null=True, upload_to=ver.utils.upload_versec, verbose_name='Anexu')),
                ('is_end', models.BooleanField(blank=True, default=False, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verseceng', to='custom.section')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verseceng', to='employee.employee', verbose_name='Ba')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('ver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verseceng', to='ver.ver')),
            ],
        ),
    ]
