# Generated by Django 5.1.3 on 2025-02-04 08:22

import ver.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ver',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ver.utils.upload_ver, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='ver',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='eng_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Komentariu Enje&ntilde;eiru'),
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ver.utils.upload_versec, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=ver.utils.upload_versec, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=ver.utils.upload_versec, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='sec_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Komentariu Xefe Seksaun'),
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Asuntu'),
        ),
    ]
