# Generated by Django 5.1.3 on 2025-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('ver', '0002_alter_ver_file_alter_ver_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verseceng',
            name='to',
        ),
        migrations.AddField(
            model_name='verseceng',
            name='to',
            field=models.ManyToManyField(related_name='verseceng', to='employee.employee', verbose_name='Ba'),
        ),
    ]
