# Generated by Django 5.1.3 on 2025-02-05 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('ver', '0003_remove_verseceng_to_verseceng_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verseceng',
            name='to',
        ),
        migrations.AddField(
            model_name='verseceng',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verseceng', to='employee.employee', verbose_name='Ba'),
        ),
    ]
