# Generated by Django 5.1.3 on 2025-02-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('ver', '0006_remove_verseceng_to_verseceng_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verseceng',
            name='to',
        ),
        migrations.AddField(
            model_name='verseceng',
            name='to',
            field=models.ManyToManyField(null=True, related_name='verseceng', to='employee.employee', verbose_name='Ba'),
        ),
    ]
