# Generated by Django 5.1.3 on 2025-02-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('ver', '0009_remove_verseceng_to_verseceng_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerSecEngEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('verseceng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ver.verseceng')),
            ],
        ),
        migrations.AlterField(
            model_name='verseceng',
            name='to',
            field=models.ManyToManyField(null=True, related_name='verseceng', through='ver.VerSecEngEmployee', to='employee.employee', verbose_name='Ba'),
        ),
    ]
