# Generated by Django 5.1.3 on 2025-02-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver', '0010_versecengemployee_alter_verseceng_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='versecengemployee',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
