# Generated by Django 5.1.3 on 2025-02-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ver', '0011_versecengemployee_date_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versecengemployee',
            name='date_assigned',
        ),
    ]
