# Generated by Django 5.1.3 on 2025-02-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver', '0012_remove_versecengemployee_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vertracks',
            name='stages',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
