# Generated by Django 5.1.3 on 2025-02-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_year_options'),
        ('ver', '0013_alter_vertracks_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ver',
            name='sec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to='custom.section', verbose_name='Seksaun'),
        ),
    ]
