# Generated by Django 5.1.3 on 2025-04-07 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_year_options'),
        ('ver', '0015_remove_ver_cont_remove_ver_inv_ver_eval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ver',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to='custom.position', verbose_name='Pozisaun'),
        ),
    ]
