# Generated by Django 5.1.3 on 2025-04-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ver', '0016_ver_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ver',
            name='pos',
        ),
    ]
