# Generated by Django 5.1.3 on 2025-04-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_email_alter_employee_phone_and_more'),
        ('ver', '0018_ver_pos_verseceng_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ver',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='verseceng',
            name='pos',
        ),
        migrations.AddField(
            model_name='ver',
            name='epos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ver', to='employee.employeepos', verbose_name='Pozisaun'),
        ),
        migrations.AddField(
            model_name='verseceng',
            name='epos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verseceng', to='employee.employeepos', verbose_name='Pozisaun'),
        ),
    ]
