# Generated by Django 5.1.3 on 2025-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ver', '0021_remove_verseceng_is_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseceng',
            name='status',
            field=models.CharField(choices=[('PASA', 'Pasa'), ('DEVOLVE', 'Devolve')], default='PASA', max_length=10, verbose_name='Rezultadu Verifikasaun'),
        ),
    ]
