# Generated by Django 4.0 on 2024-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpv',
            name='is_get_dna',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
