# Generated by Django 4.0 on 2024-04-10 05:42

from django.db import migrations, models
import finance.utils


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cpv_is_get_dna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_ev, verbose_name='Anexu'),
        ),
        migrations.AlterField(
            model_name='finfiles',
            name='file',
            field=models.FileField(null=True, upload_to=finance.utils.upload_fin_files, verbose_name='Anexu'),
        ),
        migrations.AlterField(
            model_name='prt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_prt, verbose_name='Anexu'),
        ),
    ]
