# Generated by Django 4.0 on 2024-04-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_is_sgp_alter_invoice_file_and_more'),
        ('finance', '0003_alter_ev_file_alter_finfiles_file_alter_prt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po', to='invoice.invoice', verbose_name='Invoice'),
        ),
    ]
