# Generated by Django 4.2.13 on 2024-07-09 06:05

from django.db import migrations, models
import django.db.models.deletion
import finance.utils


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_po_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpv',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_cpv, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='cpv',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeru CPV'),
        ),
        migrations.AlterField(
            model_name='cpv',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpv', to='project.project', verbose_name='Projetu'),
        ),
        migrations.AlterField(
            model_name='cpvletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_cpv_let, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='cpvletter',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeru Referensia'),
        ),
        migrations.AlterField(
            model_name='cpvletter',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='cpvreq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_cpvreq, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='cpvreq',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numeru Rekizasaun CPV'),
        ),
        migrations.AlterField(
            model_name='cpvreq',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpvreq', to='project.project', verbose_name='Projetu'),
        ),
        migrations.AlterField(
            model_name='cpvreq',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='ev',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_ev, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='finfiles',
            name='file',
            field=models.FileField(null=True, upload_to=finance.utils.upload_fin_files, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='po',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_po, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='po',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='Numeru PO'),
        ),
        migrations.AlterField(
            model_name='poletter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_po_let, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='poletter',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='prt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=finance.utils.upload_prt, verbose_name='Aneksu'),
        ),
    ]
