# Generated by Django 4.2.13 on 2024-08-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_cpv_file_alter_cpv_number_alter_cpv_proj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpv',
            name='status',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
