# Generated by Django 5.1.1 on 2024-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_cpv_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ev',
            name='is_send',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
