# Generated by Django 5.1.1 on 2024-10-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_ev_is_read_ev_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev',
            name='is_receive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
