# Generated by Django 5.1.1 on 2024-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_ev_is_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpv',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numeru CPV'),
        ),
        migrations.AlterField(
            model_name='cpvletter',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
        migrations.AlterField(
            model_name='cpvreq',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numeru Rekizasaun CPV'),
        ),
        migrations.AlterField(
            model_name='ev',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='po',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru PO'),
        ),
        migrations.AlterField(
            model_name='poletter',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='prt',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='tpo',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
    ]
