# Generated by Django 4.0 on 2024-01-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contract', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phys_prog', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('desc', models.CharField(max_length=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('com_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('com_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('bal_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymenthist', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Tinan Fiskal')),
                ('com_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('com_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('bal_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskrisaun')),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('is_end', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentfiscal', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phys_prog', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prog. Fiziku')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Montante')),
                ('com_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('com_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('bal_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskrisaun')),
                ('is_lock', models.BooleanField(default=False, null=True)),
                ('is_ready', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='contract.contract')),
                ('contyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='contract.contractyear')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='invoice.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
