# Generated by Django 4.2.13 on 2024-07-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phys_prog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Progresu Fiziku'),
        ),
    ]
