# Generated by Django 5.1.3 on 2025-06-04 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_amendment_number_alter_amendmentperiod_number_and_more'),
        ('payment', '0002_alter_payment_phys_prog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Progresu Fiziku Atual')),
                ('date', models.DateField(blank=True, null=True)),
                ('Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physicalprogress', to='contract.contract')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
