# Generated by Django 5.1.3 on 2025-06-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_physicalprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalprogress',
            old_name='Payment',
            new_name='payment',
        ),
    ]
