# Generated by Django 5.1.3 on 2025-06-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_payment_physicalprogress_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalprogress',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physicalprogress', to='payment.payment'),
        ),
    ]
