# Generated by Django 5.1.3 on 2025-06-04 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_amendment_number_alter_amendmentperiod_number_and_more'),
        ('payment', '0005_alter_physicalprogress_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalprogress',
            name='payment',
        ),
        migrations.AddField(
            model_name='physicalprogress',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physicalprogress', to='contract.contract'),
        ),
    ]
