# Generated by Django 5.1.3 on 2025-10-03 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_year_options'),
        ('payment', '0007_paymentportal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentportal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Montante'),
        ),
        migrations.AlterField(
            model_name='paymentportal',
            name='pcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentportal', to='custom.pcategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='paymentportal',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Persentajem'),
        ),
        migrations.AlterField(
            model_name='paymentportal',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentportal', to='custom.year', verbose_name='Tinan'),
        ),
    ]
