# Generated by Django 5.1.3 on 2025-11-24 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_ptypes'),
        ('payment', '0008_alter_paymentportal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentportal',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paymentportal', to='custom.program', verbose_name='Programa'),
        ),
    ]
