# Generated by Django 5.1.3 on 2025-02-13 02:15

import django.db.models.deletion
import insp.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0008_alter_amendment_number_alter_amendmentperiod_number_and_more'),
        ('custom', '0004_alter_year_options'),
        ('employee', '0001_initial'),
        ('invoice', '0021_invlet_is_adn_back'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='Numeru')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Asuntu')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Ikus')),
                ('file', models.FileField(blank=True, null=True, upload_to=insp.utils.upload_insp, verbose_name='Aneksu')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Komentariu UVIP')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back', models.BooleanField(blank=True, default=False, null=True)),
                ('back_comment', models.TextField(blank=True, null=True, verbose_name='Komentariu')),
                ('is_end', models.BooleanField(blank=True, default=False, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('cont', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insp', to='contract.contract')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insp', to='invoice.invoice')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insp', to='custom.section', verbose_name='Seksaun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspSecEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, null=True, verbose_name='Numeru')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Asuntu')),
                ('date', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Deskrisaun')),
                ('file', models.FileField(blank=True, null=True, upload_to=insp.utils.upload_inspsec, verbose_name='Aneksu')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('is_send_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_eng_back', models.BooleanField(blank=True, default=False, null=True)),
                ('is_eng_read', models.BooleanField(blank=True, default=False, null=True)),
                ('eng_comments', models.TextField(blank=True, null=True, verbose_name='Komentariu Enje&ntilde;eiru')),
                ('file2', models.FileField(blank=True, null=True, upload_to=insp.utils.upload_inspsec, verbose_name='Aneksu')),
                ('sec_comments', models.TextField(blank=True, null=True, verbose_name='Komentariu Xefe Seksaun')),
                ('file3', models.FileField(blank=True, null=True, upload_to=insp.utils.upload_inspsec, verbose_name='Aneksu')),
                ('is_end', models.BooleanField(blank=True, default=False, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('insp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspseceng', to='insp.insp')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspseceng', to='custom.section')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspSecEngEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('inspseceng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insp.inspseceng')),
            ],
        ),
        migrations.AddField(
            model_name='inspseceng',
            name='to',
            field=models.ManyToManyField(null=True, related_name='inspseceng', through='insp.InspSecEngEmployee', to='employee.employee', verbose_name='Ba'),
        ),
        migrations.CreateModel(
            name='InspTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_start', models.BooleanField(blank=True, default=False, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('is_uvip_out', models.BooleanField(blank=True, default=False, null=True)),
                ('date_uvip_out', models.DateField(blank=True, null=True)),
                ('is_sec_in_1', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_in_1', models.DateField(blank=True, null=True)),
                ('is_sec_out_1', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_out_1', models.DateField(blank=True, null=True)),
                ('is_eng_in', models.BooleanField(blank=True, default=False, null=True)),
                ('date_eng_in', models.DateField(blank=True, null=True)),
                ('is_eng_out', models.BooleanField(blank=True, default=False, null=True)),
                ('date_eng_out', models.DateField(blank=True, null=True)),
                ('is_sec_in_2', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_in_2', models.DateField(blank=True, null=True)),
                ('is_sec_out_2', models.BooleanField(blank=True, default=False, null=True)),
                ('date_sec_out_2', models.DateField(blank=True, null=True)),
                ('is_uvip_in', models.BooleanField(blank=True, default=False, null=True)),
                ('date_uvip_in', models.DateField(blank=True, null=True)),
                ('is_end', models.BooleanField(blank=True, default=False, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('stages', models.CharField(blank=True, max_length=250, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('insp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insptracks', to='insp.insp')),
            ],
        ),
    ]
