# Generated by Django 5.1.3 on 2025-05-05 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_email_alter_employee_phone_and_more'),
        ('insp', '0003_remove_inspseceng_epos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspseceng',
            name='epos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspsegeng', to='employee.employeepos', verbose_name='Pozisaun'),
        ),
    ]
