# Generated by Django 5.1.3 on 2025-05-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insp', '0004_inspseceng_epos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspseceng',
            name='epos',
        ),
    ]
