# Generated by Django 5.1.3 on 2025-04-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepos',
            name='cat',
            field=models.CharField(blank=True, choices=[('Verifikasaun', 'Inspeksaun'), ('Verifikasaun', 'Inspeksaun')], max_length=16, null=True),
        ),
    ]
