# Generated by Django 5.1.3 on 2025-04-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeepos_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeepos',
            name='cat',
            field=models.CharField(blank=True, choices=[('Verifikasaun', 'Verifikasaun'), ('Inspeksaun', 'Inspeksaun')], max_length=16, null=True, verbose_name='Category'),
        ),
    ]
