# Generated by Django 4.0 on 2024-02-15 00:23

from django.db import migrations, models
import proc.utils


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=proc.utils.upload_proc, verbose_name='Anexu (.pdf)'),
        ),
    ]
