# Generated by Django 5.0.6 on 2024-06-12 02:06

import proc.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0002_alter_proclet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='Numeru Referensia'),
        ),
        migrations.AlterField(
            model_name='procfiles',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dekrisaun Aneksu'),
        ),
        migrations.AlterField(
            model_name='procfiles',
            name='file',
            field=models.FileField(null=True, upload_to=proc.utils.upload_procfiles, verbose_name='Aneksu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='proclet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=proc.utils.upload_proc, verbose_name='Aneksu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='proclet',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='Numeru Referensia'),
        ),
        migrations.AlterField(
            model_name='proclet',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='proctrack',
            name='is_result',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rezultadu'),
        ),
    ]
