# Generated by Django 4.2.13 on 2024-07-09 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0003_alter_proc_number_alter_procfiles_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proc', to='project.project', verbose_name='Projetu'),
        ),
        migrations.AlterField(
            model_name='proclet',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proclet', to='proc.letto', verbose_name='Diriji ba'),
        ),
    ]
