# Generated by Django 5.1.1 on 2024-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0004_alter_proc_proj_alter_proclet_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proc',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
    ]
