# Generated by Django 5.1.1 on 2024-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0005_alter_proc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclet',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
    ]
