# Generated by Django 4.0 on 2024-01-10 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=600, null=True, verbose_name='Naran Projetu')),
                ('name2', models.CharField(max_length=600, null=True, verbose_name='Naran Projetu-2')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deskrisaun')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('is_lock', models.BooleanField(default=False, null=True)),
                ('is_ready', models.BooleanField(default=False, null=True)),
                ('is_eval', models.BooleanField(default=False, null=True)),
                ('is_cont', models.BooleanField(default=False, null=True)),
                ('is_adn', models.BooleanField(default=False, null=True, verbose_name='Verifika Liu ADN')),
                ('is_end', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.book', verbose_name='Livru')),
                ('capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.capital')),
                ('capital2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.capital2', verbose_name='New Capital')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.fund', verbose_name='Fundus')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.division', verbose_name='Dono Projetu')),
                ('pcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.pcat', verbose_name='Kat. MOP')),
                ('pcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.pcategory', verbose_name='Kategoria')),
                ('ptype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.ptype', verbose_name='Tipu')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.sector', verbose_name='Setor')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.statusplan')),
                ('statusproj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.statusproj', verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.year', verbose_name='Tinan')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('start_lng', models.CharField(blank=True, max_length=20, null=True)),
                ('end_lat', models.CharField(blank=True, max_length=20, null=True)),
                ('end_lng', models.CharField(blank=True, max_length=20, null=True)),
                ('administrativepost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name='Posto')),
                ('aldeia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.aldeia', verbose_name='Aldeia')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Municipiu')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectloc', to='project.project')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name='Suco')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Estimasaun Dono')),
                ('adn', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='ADN')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('is_lock', models.BooleanField(default=False, null=True)),
                ('is_ready', models.BooleanField(default=False, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectest', to='project.project')),
            ],
        ),
    ]
