# Generated by Django 4.0 on 2024-02-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name2',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Naran Projetu-2'),
        ),
    ]
