# Generated by Django 4.0 on 2024-04-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('project', '0002_alter_project_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.pcategory', verbose_name='Kategoria'),
        ),
    ]
