# Generated by Django 5.0.6 on 2024-06-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_pcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='capital2',
        ),
    ]
