# Generated by Django 5.1.3 on 2025-02-05 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_year_options'),
        ('project', '0004_remove_project_capital2'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alocate_bd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Alokasaun Orsamentu'),
        ),
        migrations.AddField(
            model_name='project',
            name='code_act',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Kodigu Aktividade'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='year_alocate_bd',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025, verbose_name='Tinan Alokasaun Orsamentu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.capital', verbose_name='Kapital'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Kodigu Projetu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.division', verbose_name='Donu Projetu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pcat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.pcat', verbose_name='Kategoria MOP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.statusplan', verbose_name='Status Planu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='statusproj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.statusproj', verbose_name='Status Orsamentu'),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.year', verbose_name='Tinan Projetu'),
        ),
        migrations.AlterField(
            model_name='projectest',
            name='owner',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Estimasaun Donu'),
        ),
        migrations.AlterField(
            model_name='projectloc',
            name='administrativepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.administrativepost', verbose_name='Postu'),
        ),
        migrations.AlterField(
            model_name='projectloc',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Munisipiu'),
        ),
        migrations.AlterField(
            model_name='projectloc',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.village', verbose_name='Suku'),
        ),
    ]
