# Generated by Django 5.1.3 on 2025-11-21 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_program'),
        ('project', '0005_project_alocate_bd_project_code_act_project_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.program', verbose_name='Programa'),
        ),
    ]
