# Generated by Django 5.1.3 on 2025-11-24 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_ptypes'),
        ('project', '0006_project_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ptypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='custom.ptypes', verbose_name='Tipu Projetu'),
        ),
    ]
