# Generated by Django 5.1.3 on 2025-12-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_ptypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='adn.png', null=True, upload_to='image_data')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectimg', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project Galleria',
            },
        ),
    ]
