# Generated by Django 4.0 on 2024-01-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naran')),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nu. Registrasaun')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nu. Telemovel')),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enderesu')),
                ('type', models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=15, null=True, verbose_name='Kategoria')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('lat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude')),
                ('lng', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.country', verbose_name='Nasaun')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality', verbose_name='Municipiu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
