# Generated by Django 4.0 on 2024-01-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        ('eval', '0001_initial'),
        ('finance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ver', '0001_initial'),
        ('employee', '0001_initial'),
        ('invoice', '0001_initial'),
        ('proc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerJustify2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_uvip', models.BooleanField(default=False, null=True)),
                ('is_sec', models.BooleanField(default=False, null=True)),
                ('is_eng', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verjustify2', to='employee.employee')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verjustify2', to='custom.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('ver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verjustify2', to='ver.ver')),
            ],
        ),
        migrations.CreateModel(
            name='VerJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_uvip', models.BooleanField(default=False, null=True)),
                ('is_sec', models.BooleanField(default=False, null=True)),
                ('is_eng', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verjustify', to='employee.employee')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verjustify', to='custom.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('ver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verjustify', to='ver.ver')),
            ],
        ),
        migrations.CreateModel(
            name='ProcJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_dna', models.BooleanField(default=False, null=True)),
                ('is_dgaf', models.BooleanField(default=False, null=True)),
                ('is_gab', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('proc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procjustify', to='proc.proc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='POJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_dna', models.BooleanField(default=False, null=True)),
                ('is_dgaf', models.BooleanField(default=False, null=True)),
                ('is_gab', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pojustify', to='finance.po')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_sup', models.BooleanField(default=False, null=True)),
                ('is_uvip', models.BooleanField(default=False, null=True)),
                ('is_gab', models.BooleanField(default=False, null=True)),
                ('is_dgaf', models.BooleanField(default=False, null=True)),
                ('is_dna', models.BooleanField(default=False, null=True)),
                ('is_dnof', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invjustify', to='invoice.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='EvalJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_uvip', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('eval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaljustify', to='eval.eval')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CPVReqJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_dnof', models.BooleanField(default=False, null=True)),
                ('is_dgaf', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('cpvreq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpvreqjust', to='finance.cpvreq')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='CPVJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_dnof', models.BooleanField(default=False, null=True)),
                ('is_dgaf', models.BooleanField(default=False, null=True)),
                ('is_gab', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('cpv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpvjustify', to='finance.cpv')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
