# Generated by Django 5.1.3 on 2025-02-14 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_year_options'),
        ('employee', '0001_initial'),
        ('insp', '0001_initial'),
        ('track', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspJustify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_uvip', models.BooleanField(default=False, null=True)),
                ('is_sec', models.BooleanField(default=False, null=True)),
                ('is_eng', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspjustify', to='employee.employee')),
                ('insp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspjustify', to='insp.insp')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspjustify', to='custom.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InspJustify2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Justifikasaun')),
                ('is_uvip', models.BooleanField(default=False, null=True)),
                ('is_sec', models.BooleanField(default=False, null=True)),
                ('is_eng', models.BooleanField(default=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspjustify2', to='employee.employee')),
                ('insp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspjustify2', to='insp.insp')),
                ('sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspjustify2', to='custom.section')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
