# Generated by Django 5.0.6 on 2024-06-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('project', '0004_remove_project_capital2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capital2',
        ),
    ]
