# Generated by Django 5.0.6 on 2024-06-11 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_delete_capital2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='custom.division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='dg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='custom.dg'),
        ),
    ]
