# Generated by Django 5.1.3 on 2025-01-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_alter_department_division_alter_division_dg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('-year',)},
        ),
    ]
