# Generated by Django 5.1.3 on 2025-11-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_year_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='Kodigu')),
                ('name', models.CharField(max_length=155, null=True, verbose_name='Programa')),
            ],
        ),
    ]
