# Generated by Django 5.1.3 on 2025-11-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
