# Generated by Django 4.0 on 2024-02-13 06:46

from django.db import migrations, models
import invoice.utils


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invlet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv_let, verbose_name='Anexu (.pdf)'),
        ),
    ]
