# Generated by Django 4.0 on 2024-04-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('invoice', '0002_alter_invlet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrecom',
            name='cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrecom', to='contract.contract'),
        ),
    ]
