# Generated by Django 4.0 on 2024-04-11 07:07

from django.db import migrations, models
import invoice.utils


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_payrecom_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_sgp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Liu ADN'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv, verbose_name='Anexu'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_recom, verbose_name='Anexu (.pdf)'),
        ),
    ]
