# Generated by Django 4.2.13 on 2024-07-09 06:05

from django.db import migrations, models
import django.db.models.deletion
import invoice.utils


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_alter_department_division_alter_division_dg'),
        ('contract', '0008_alter_amendment_number_alter_amendmentperiod_number_and_more'),
        ('invoice', '0004_invoice_is_sgp_alter_invoice_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certpay',
            name='file',
            field=models.FileField(null=True, upload_to=invoice.utils.upload_cert, verbose_name='Aneksu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='certpay',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Montante Pagamentu'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv_let, verbose_name='Aneksu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Asuntu'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resibu', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv, verbose_name='Aneksu'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='mun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Resibu', to='custom.municipality'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Montante Pagamentu'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_recom, verbose_name='Aneksu (.pdf)'),
        ),
    ]
