# Generated by Django 4.2.13 on 2024-08-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_certpay_file_alter_certpay_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_sgp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Liu SGP'),
        ),
    ]
