# Generated by Django 4.2.13 on 2024-09-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_is_sgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dnof_back_aprove',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dnof_back_create',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dnof_back_in',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dnof_back_out',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dnof_back_verify',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
