# Generated by Django 4.2.13 on 2024-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invtrack_date_dnof_back_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_aprove_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_aprove_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_create_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_create_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_verify_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_back_verify_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
