# Generated by Django 5.1.1 on 2024-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_rename_date_dnof_back_aprove_end_invtrack_date_dnof_back_apr_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certpay',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='number',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Numeru'),
        ),
    ]
