# Generated by Django 5.1.3 on 2025-02-06 00:22

import invoice.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_certpay_number_alter_invlet_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invlet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv_let, verbose_name='Aneksu Resibu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Numeru'),
        ),
    ]
