# Generated by Django 5.1.3 on 2025-02-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invlet_file_alter_invlet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certpay',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru'),
        ),
    ]
