# Generated by Django 5.1.3 on 2025-02-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_certpay_number_alter_invlet_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number_req',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='Numeru Rekizasaun'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
    ]
