# Generated by Django 5.1.3 on 2025-02-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_invoice_number_req_alter_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='number_req',
        ),
    ]
