# Generated by Django 5.1.3 on 2025-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_remove_invoice_number_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='certpay',
            name='number_req',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='Numeru Rekizasaun'),
        ),
        migrations.AlterField(
            model_name='certpay',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
    ]
