# Generated by Django 5.1.3 on 2025-02-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_certpay_number_req_alter_certpay_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecom',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='term',
            field=models.CharField(max_length=3, null=True, verbose_name='Numeru Resibu/IPC'),
        ),
    ]
