# Generated by Django 5.1.3 on 2025-02-07 07:10

import django.db.models.deletion
import invoice.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_alter_payrecom_number_alter_payrecom_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certpay',
            name='file',
            field=models.FileField(null=True, upload_to=invoice.utils.upload_cert, verbose_name='Aneksu Dokumentu(.pdf)'),
        ),
        migrations.AlterField(
            model_name='certpay',
            name='phys_prog',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Progresu Fiziku'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv_let, verbose_name='Aneksu Dokumentu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='invlet',
            name='number',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Numeru Referensia'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_recom, verbose_name='Aneksu Sertifikadu Pagamentu (.pdf)'),
        ),
        migrations.AlterField(
            model_name='payrecom',
            name='phys_prog',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Progresu Fiziku'),
        ),
        migrations.CreateModel(
            name='InvLetAdnBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True, unique=True, verbose_name='Numeru Referensia')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='Asuntu')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data Karta')),
                ('file', models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv_let, verbose_name='Aneksu Dokumentu (.pdf)')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True)),
                ('is_back', models.BooleanField(blank=True, default=False, null=True)),
                ('is_return', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Komentariu')),
                ('datetime', models.DateTimeField(null=True, verbose_name='Data Karta Simu')),
                ('hashed', models.CharField(blank=True, max_length=32, null=True)),
                ('invlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invletadnback', to='invoice.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
