# Generated by Django 5.1.3 on 2025-02-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_alter_certpay_file_alter_certpay_phys_prog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invletadnback',
            name='number',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Numeru Referensia ADN'),
        ),
    ]
