# Generated by Django 5.1.3 on 2025-02-07 09:52

import invoice.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_invletadnback_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invletadnback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.utils.upload_inv_let_dev_adn, verbose_name='Aneksu Dokumentu (.pdf)'),
        ),
    ]
