# Generated by Django 5.1.3 on 2025-02-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_alter_invletadnback_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invletadnback',
            name='invlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invletadnback', to='invoice.invlet'),
        ),
    ]
