# Generated by Django 5.1.3 on 2025-02-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_alter_invletadnback_invlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='invlet',
            name='is_adn_back',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
