# Generated by Django 5.1.3 on 2025-02-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_invlet_is_adn_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_ver',
            new_name='is_insp',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='date_dnof_back_ver_end',
            new_name='date_dnof_back_insp_end',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='date_dnof_back_ver_start',
            new_name='date_dnof_back_insp_start',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='date_ver_end',
            new_name='date_insp_end',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='date_ver_start',
            new_name='date_insp_start',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='is_dnof_back_ver_end',
            new_name='is_dnof_back_insp_end',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='is_dnof_back_ver_start',
            new_name='is_dnof_back_insp_start',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='is_ver_end',
            new_name='is_insp_end',
        ),
        migrations.RenameField(
            model_name='invtrack',
            old_name='is_ver_start',
            new_name='is_insp_start',
        ),
    ]
