# Generated by Django 5.1.3 on 2025-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_rename_is_ver_invoice_is_insp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_sgp',
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_cna',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Liu CNA'),
        ),
    ]
