# Generated by Django 5.1.3 on 2025-05-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_remove_invoice_is_sgp_invoice_is_cna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certpay',
            name='number_req',
            field=models.CharField(max_length=4, null=True, unique=True, verbose_name='Numeru Serifikadu'),
        ),
    ]
