# Generated by Django 5.1.3 on 2025-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_alter_certpay_number_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_sgp',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Liu SGP'),
        ),
    ]
