# Generated by Django 5.1.3 on 2025-05-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_invoice_is_sgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtrack',
            name='date_gab_app',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_gap_app',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
