# Generated by Django 5.1.3 on 2025-05-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_invtrack_date_gab_app_invtrack_is_gap_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtrack',
            name='date_dgaf_in_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dgaf_out_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dgaf_in_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dgaf_out_1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
