# Generated by Django 5.1.3 on 2025-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_invtrack_date_dgaf_in_1_invtrack_date_dgaf_out_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtrack',
            name='date_dna_in_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='date_dna_out_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dna_in_1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dna_out_1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
