# Generated by Django 5.1.3 on 2025-05-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_invtrack_date_dna_in_1_invtrack_date_dna_out_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invtrack',
            name='date_dgaf_in_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='date_dgaf_out_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='date_dna_in_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='date_dna_out_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='is_dgaf_in_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='is_dgaf_out_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='is_dna_in_1',
        ),
        migrations.RemoveField(
            model_name='invtrack',
            name='is_dna_out_1',
        ),
    ]
