# Generated by Django 5.1.3 on 2025-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0029_remove_invtrack_date_dgaf_in_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invtrack',
            name='date_dnof_middle_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invtrack',
            name='is_dnof_middle_out',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
